CREATE DATABASE AgroFreight;
GO
USE AgroFreight;
GO

CREATE TABLE Dim_Date
(
    DateID INTEGER IDENTITY(1,1) PRIMARY KEY,
    RecordDate DATE NOT NULL,
    Month INTEGER NOT NULL,
    Year INTEGER NOT NULL,
    IsHarvestSeason BIT NOT NULL
);

CREATE TABLE Dim_Route
(
    RouteID INTEGER IDENTITY(1,1) PRIMARY KEY,
    Origin VARCHAR(100) NOT NULL,
    Destination VARCHAR(100) NOT NULL,
    DistanceKM INTEGER NOT NULL
);

CREATE TABLE Dim_Vehicle
(
    VehicleID INTEGER IDENTITY(1,1) PRIMARY KEY,
    PlateNumber VARCHAR(64) NOT NULL,
    VehicleType VARCHAR(50) NOT NULL,
    Capacity INTEGER NOT NULL
);

CREATE TABLE Log_Errors
(
    ErrorID INTEGER IDENTITY(1,1) PRIMARY KEY,
    RawData NVARCHAR(MAX) NOT NULL,
    ErrorMessage VARCHAR(255) NOT NULL,
    ErrorDate DATE NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Fact_Freight
(
    FreightID INTEGER IDENTITY(1,1) PRIMARY KEY,
    DepartureDateID INTEGER NOT NULL,
    ArrivalDateID INTEGER NOT NULL,
    RouteID INTEGER NOT NULL,
    VehicleID INTEGER NOT NULL,
    FreightValue DECIMAL(10, 2) NOT NULL,
    DieselPrice DECIMAL(10, 2) NOT NULL,
    WeightTon DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (DepartureDateID) REFERENCES Dim_Date(DateID),
    FOREIGN KEY (ArrivalDateID) REFERENCES Dim_Date(DateID),
    FOREIGN KEY (RouteID) REFERENCES Dim_Route(RouteID),
    FOREIGN KEY (VehicleID) REFERENCES Dim_Vehicle(VehicleID)
);
